### ISSUE TITLE
Clean - Create Project

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#101]
1. Review #24  again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task - it is for masters, but many things will be applicable to this page as well.
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**method 1 - to get responsibility list to bind dropdown**

SELECT 
    1 AS [C1], 
    [Extent2].[Id] AS [Id], 
    [Extent2].[Title] AS [Title]
    FROM  [dbo].[ProjectMembership] AS [Extent1]
    INNER JOIN [dbo].[Project] AS [Extent2] ON [Extent1].[ProjectId] = [Extent2].[Id]
    WHERE ([Extent1].[UserId] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)


**method 2 - to get user list for typehead**

SELECT 
    1 AS [C1], 
    [Extent2].[Id] AS [Id], 
    [Extent1].[FirstName] + N' ' + [Extent1].[LastName] AS [C2], 
     CAST( [Extent2].[Role] AS int) AS [C3]
    FROM  [dbo].[Person] AS [Extent1]
    INNER JOIN [dbo].[User] AS [Extent2] ON [Extent1].[Id] = [Extent2].[PersonId]
    WHERE ((( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__0))), LTRIM(RTRIM(LOWER([Extent1].[FirstName])))) AS int)) = 1) OR (( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__1))), LTRIM(RTRIM(LOWER([Extent1].[LastName])))) AS int)) = 1) OR (( CAST(CHARINDEX(LTRIM(RTRIM(LOWER(@p__linq__2))), LTRIM(RTRIM(LOWER([Extent2].[Email])))) AS int)) = 1)) AND ( NOT ((1 =  CAST( [Extent2].[Role] AS int)) AND ( CAST( [Extent2].[Role] AS int) IS NOT NULL)))


**method 3 - to create project (1st one for add project & 2nd is for add membership in single post request)**

**for add project**

INSERT [dbo].[Project]([Title], [ProjectCode], [CreatedOn], [UpdatedOn])
VALUES (@0, @1, @2, @3)
SELECT [Id]
FROM [dbo].[Project]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()

**for add project membership**

INSERT [dbo].[ProjectMembership]([ProjectId], [UserId], [IsActive], [ResponsibilityId], [CreatedOn], [UpdatedOn])
VALUES (@0, @1, @2, @3, @4, @5)
SELECT [Id]
FROM [dbo].[ProjectMembership]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()

**Comment by AAndharia** [comment]
1. i think exception handling related code can be handled directly in service in better way, right now logic to send message or generate toast is in controller method.
2. check variable names in GetProjectResponsibilities service method
3. LookupService.GetUserList - we need more meaningful name for this method. Also this should load only active users - user with role = admin
4. method 1 - to get responsibility list to bind dropdown - this is not relevant, it should load data from Enum

**Comment by jmervana** [comment]
@AAndharia 
1. Done please verify

2. Done please verify

3. Done please verify

4. its my mistake this is not for get responsibility , its for get project list for menu dropdown of project.

**Comment by AAndharia** [comment]
LookupService.GetUserList - getuserlistfortypehead is still not looking meaningful to me. try to find 3-4 other options, give me on Skype and let's see.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
Verified. Closing.
